---
default:
  Project: PHIAT-YLL
  Title: Popuation Health Impact Assessment Tools for years of life lost
  Description:
  Version: 0.1.0
  Date: 2019-10-15
  Funding: CIHR FRN 162222
  Role:
  variables: !expr utils::read.csv(file.path(getwd(),"Worksheets/variables.csv"))
  variable_details: !expr utils::read.csv(file.path(getwd(),"Worksheets/variable_details.csv"))
  modules: !expr utils::read.csv(file.path(getwd(),"Modules/modules.csv"))
  data_type:
    ".csv"
    # allowable data_type: .csv, .rdata, .sas7bdat (todo)
  data_dir:
    !expr file.path(getwd(),"Data", "test")
    # data_dir is the directory where data will be saved.
  data:
    cchs2001_p: !expr file.path(getwd(), "Data/cchs-82M0013-E-2001-c1-1-general-file_F1.csv")
    cchs2003_p: !expr file.path(getwd(), "Data/cchs-82M0013-E-2003-c2-1-GeneralFile_F1.csv")
    cchs2005_p: !expr file.path(getwd(), "Data/cchs-82M0013-E-2005-c3-1-main-file_F1.csv")
    cchs2007_2008_p: !expr file.path(getwd(), "Data/cchs-E-2007-2008-AnnualComponent_F1.csv")
    cchs2009_2010_p: !expr file.path(getwd(), "Data/CCHS-82M0013-E-2009-2010-Annualcomponent_F1.csv")
    cchs2011_2012_p: !expr file.path(getwd(), "Data/cchs-82M0013-E-2011-2012-Annual-component_F1.csv")
    cchs2013_2014_p: !expr file.path(getwd(), "Data/cchs-82M0013-E-2013-2014-Annual-component_F1.csv")
  Authors:
    person:
      given: Doug
      family: Manuel
      email: dmanuel@ohri.ca
      inst: The Ottawa Hospital Research Institute
      role:
        - aut
        - cre
      ORCID: 0000-0003-0912-0845

RData:
  variables: !expr utils::read.csv(file.path(getwd(),"Worksheets/variables.csv"))
  variable_details: !expr utils::read.csv(file.path(getwd(),"Worksheets/variable_details.csv"))
  modules: !expr utils::read.csv(file.path(getwd(),"Modules/modules.csv"))
  data_type: ".RData"
  data_dir: !expr file.path(getwd(),"Data", "test")
  data:
    cchs2001_p: !expr file.path(getwd(), "Data/test/cchs2001_p.RData")
    cchs2003_p: !expr file.path(getwd(), "Data/test/cchs2003_p.RData")
    cchs2005_p: !expr file.path(getwd(), "Data/test/cchs2005_p.RData")
    cchs2007_2008_p: !expr file.path(getwd(), "Data/test/cchs2007_2008_p.RData")
    cchs2009_2010_p: !expr file.path(getwd(), "Data/test/cchs2009_2010_p.RData")
    cchs2011_2012_p: !expr file.path(getwd(), "Data/test/cchs2011_2012_p.RData")
    cchs2013_2014_p: !expr file.path(getwd(), "Data/test/cchs2013_2014_p.RData")
# see local_evironment.yml for a template to store local files and directories.
# Modify .gitingore to exclude these files from git, if desired.
# Access local_enironment.ymml by modifying the code below.
# local_environment:

#data_type: "<DATA TYPE BEING LOADED>"
#variables: !expr config::get("variables", file = "<PATH TO NEW CONFIG>")
#variable_details: !expr config::get("variable_details", file = "<PATH TO NEW CONFIG>")
#modules: !expr config::get("modules", file = "<PATH TO NEW CONFIG>")
#data_dir: !expr config::get("data_dir", file = "<PATH TO NEW CONFIG>")
#data: !expr config::get("data", file = "<PATH TO NEW CONFIG>")
